version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: dw_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accurate-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_dw_data:/var/lib/postgresql/data
      - ./warehouse/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      - airflow-db
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow:/opt/project
    env_file:
      - .env
    volumes:
      - .:/opt/project
      - ./orchestration/dags:/opt/airflow/dags
      - ./orchestration/config:/opt/airflow/config
      - ./orchestration/scripts/init_airflow.sh:/init.sh
    command: >
        bash -c "
          airflow db migrate &&
          airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
          bash /init.sh &&
          airflow webserver
        "
    ports:
      - "8080:8080"

  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

volumes:
  airflow_pgdata:
  postgres_dw_data:
