version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: branch
      - name: customer
      - name: customercategory
      - name: invoice
      - name: invoicedetail
      - name: item
      - name: itemcategory
      - name: warehouse